version: '3.8'

services:
  postgresql:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: social_media
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  spring_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

volumes:
  postgresql_data: