name: JavaDoc

on:
  push:
    paths:
      - 'src/main/java/**'
      - '.github/workflows/javadoc.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Generate JavaDoc
        run: mvn javadoc:javadoc

      - name: Copy JavaDoc to project directory
        run: cp -R target/site/apidocs ${{ github.workspace }}/docs
